services:
  mysql:
    image: mysql:8.0
    container_name: mysql_boot
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a
      MYSQL_DATABASE: live_chat
      MYSQL_USER: a
      MYSQL_PASSWORD: a
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
