server:
  port: 8090

spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: chat-group-${random.uuid}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

jwt:
  secret: "a"

# custom
app:
  redis-channel: "stream-updates"

kafka:
  topic:
    raw-chats: "raw-chats"
    analysis-result: "analysis-result"